// <auto-generated />
using System;
using AssetFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssetFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517172128_AddPasswordResetToken")]
    partial class AddPasswordResetToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssetFlow.Domain.Entities.Affectation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAffectation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateRetour")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Courante");

                    b.Property<int>("MaterielId")
                        .HasColumnType("integer");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<int?>("ProjetId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteAffectee")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteRetournee")
                        .HasColumnType("integer");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterielId");

                    b.HasIndex("ProjetId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Affectations");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.ArticleHistorique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateEvenement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TypeEvenement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("DateEvenement");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("ArticleHistoriques");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.ArticleIndividuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AffectationId")
                        .HasColumnType("integer");

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer");

                    b.Property<int>("Etat")
                        .HasColumnType("integer");

                    b.Property<int>("MaterielId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AffectationId");

                    b.HasIndex("CommandeId");

                    b.HasIndex("MaterielId");

                    b.HasIndex("NumeroSerie")
                        .IsUnique();

                    b.ToTable("ArticlesIndividuels");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioData")
                        .HasColumnType("text");

                    b.Property<int>("AudioDurationSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Content")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId", "ReceiverId", "SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFinGarantie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLivraison")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterielId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("QuantiteAchetee")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("MaterielId");

                    b.HasIndex("NumeroCommande")
                        .IsUnique();

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.CommentaireMateriel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterielId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterielId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("CommentairesMateriel", (string)null);
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.DemandeAchat", b =>
                {
                    b.Property<int>("IdDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDemande"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DemandeurNom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MotifRefus")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("VuParAchatLe")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdDemande");

                    b.HasIndex("UserId");

                    b.ToTable("DemandeAchat", (string)null);
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Fournisseur", b =>
                {
                    b.Property<int>("IdFournisseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFournisseur"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("CommandesTotales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DerniereCommande")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ScoreFiabilite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TauxLivraisonATemps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdFournisseur");

                    b.ToTable("Fournisseur", (string)null);
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffectationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("CommentairesResolution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DateIncident")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TypeIncident")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Urgence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AffectationId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.LigneDemande", b =>
                {
                    b.Property<int>("IdLigne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLigne"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdDemande")
                        .HasColumnType("integer");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdLigne");

                    b.HasIndex("IdDemande");

                    b.ToTable("LigneDemande");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Materiel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Emplacement")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("QuantiteMin")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteStock")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Materiels");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AffectationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstLue")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Niveau")
                        .HasColumnType("integer");

                    b.Property<string>("RoleDestinataire")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AffectationId");

                    b.HasIndex("DateCreation");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("EstLue", "RoleDestinataire");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.OffreAchat", b =>
                {
                    b.Property<Guid>("IdOffre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("ContenuPdf")
                        .HasColumnType("bytea");

                    b.Property<string>("DelaiLivraison")
                        .HasColumnType("text");

                    b.Property<bool>("EstChoisie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("FraisLivraison")
                        .HasColumnType("text");

                    b.Property<string>("Garantie")
                        .HasColumnType("text");

                    b.Property<int>("IdDemande")
                        .HasColumnType("integer");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PrixTotal")
                        .HasColumnType("text");

                    b.Property<long>("Taille")
                        .HasColumnType("bigint");

                    b.HasKey("IdOffre");

                    b.HasIndex("IdDemande");

                    b.ToTable("OffreAchat", (string)null);
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Budget")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Moyenne");

                    b.Property<string>("Responsable")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Planifie");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("Projets", (string)null);
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FaceKeypoints")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("KeycloakId")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs", (string)null);
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Affectation", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Materiel", "Materiel")
                        .WithMany("Affectations")
                        .HasForeignKey("MaterielId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetFlow.Domain.Entities.Project", "Projet")
                        .WithMany("Affectations")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssetFlow.Domain.Entities.User", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Materiel");

                    b.Navigation("Projet");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.ArticleHistorique", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.ArticleIndividuel", "Article")
                        .WithMany("Historiques")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetFlow.Domain.Entities.User", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Article");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.ArticleIndividuel", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Affectation", "Affectation")
                        .WithMany("Articles")
                        .HasForeignKey("AffectationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssetFlow.Domain.Entities.Commande", "Commande")
                        .WithMany("Articles")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetFlow.Domain.Entities.Materiel", "Materiel")
                        .WithMany()
                        .HasForeignKey("MaterielId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Affectation");

                    b.Navigation("Commande");

                    b.Navigation("Materiel");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetFlow.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Commande", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssetFlow.Domain.Entities.Materiel", "Materiel")
                        .WithMany()
                        .HasForeignKey("MaterielId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fournisseur");

                    b.Navigation("Materiel");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.CommentaireMateriel", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Materiel", "Materiel")
                        .WithMany()
                        .HasForeignKey("MaterielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetFlow.Domain.Entities.User", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materiel");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.DemandeAchat", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Incident", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Affectation", "Affectation")
                        .WithMany()
                        .HasForeignKey("AffectationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetFlow.Domain.Entities.ArticleIndividuel", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Affectation");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.LigneDemande", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.DemandeAchat", "Demande")
                        .WithMany("Lignes")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Affectation", "Affectation")
                        .WithMany()
                        .HasForeignKey("AffectationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssetFlow.Domain.Entities.User", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Affectation");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.OffreAchat", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.DemandeAchat", "Demande")
                        .WithMany("Offres")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Affectation", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.ArticleIndividuel", b =>
                {
                    b.Navigation("Historiques");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Commande", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.DemandeAchat", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Offres");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Materiel", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Project", b =>
                {
                    b.Navigation("Affectations");
                });
#pragma warning restore 612, 618
        }
    }
}
