events {}
http {
    include mime.types;
    types {
        application/wasm wasm;
        application/octet-stream dll;
    }
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        # Fichiers framework Blazor
        location /_framework/ {
            try_files $uri =404;
            add_header Cache-Control "no-cache";
        }

        # Fichiers statiques
        location ~* \.(js|css|png|jpg|svg|ico|json|wasm|dll|dat|blat)$ {
            try_files $uri =404;
            add_header Cache-Control "public, max-age=3600";
        }

        # Routing Blazor — toutes les autres routes
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}