events {}
http {
    include mime.types;
    types {
        application/wasm wasm;
    }
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location /_framework/ {
            try_files $uri =404;
            add_header Cache-Control "no-cache";
            gzip_static on;
        }

        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-cache";
        }
    }
}